import { PrismaClient } from '@prisma/client'

const globalForPrisma = globalThis as unknown as { prisma: PrismaClient | undefined }

const prismaClientSingleton = () => {
    const client = new PrismaClient({
        log: process.env.NODE_ENV === 'development' ? ['error', 'warn'] : ['error'],
    })

    // [FIX] Add backwards-compatible aliases for existing code using old model names
    // This allows `prisma.User` to work while Auth.js uses `prisma.User` (Standardized)
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    // [FIX] Add aliases for PascalCase usage (Refactor) -> camelCase (Prisma Default)
    const extendedClient = client as any

    // Explicitly mapping PascalCase (used in app) to camelCase (generated by Prisma)
    extendedClient.User = client.user
    extendedClient.Account = client.account
    extendedClient.Session = client.session
    extendedClient.VerificationToken = client.verificationToken
    extendedClient.RolePermission = client.rolePermission

    // Legacy aliases (for backward compatibility if any left)
    extendedClient.users = client.user
    extendedClient.accounts = client.account
    extendedClient.sessions = client.session
    extendedClient.verification_tokens = client.verificationToken

    return extendedClient as PrismaClient
}

export const prisma = globalForPrisma.prisma ?? prismaClientSingleton()

if (process.env.NODE_ENV !== 'production') {
    globalForPrisma.prisma = prisma
}

export default prisma

