const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

async function main() {
    console.log('🧹 Starting User Cleanup Protocol (JS Mode)...');

    try {
        // 1. Delete dependent auth tables first
        // Note: Using camelCase model names as generated by Prisma from PascalCase models
        // If models are 'model Session', 'model Account', 'model User'

        console.log('Deleting Sessions...');
        // Try-catch blocks for individual tables in case of naming mismatch, 
        // though 'session', 'account', 'user' is standard Prisma naming for these models.

        try {
            if (prisma.session) await prisma.session.deleteMany({});
            else if (prisma.sessions) await prisma.sessions.deleteMany({}); // fallback
        } catch (e) {
            console.log('Note: Error deleting sessions (might be empty or wrong model name):', e.message);
        }

        console.log('Deleting Accounts...');
        try {
            if (prisma.account) await prisma.account.deleteMany({});
            else if (prisma.accounts) await prisma.accounts.deleteMany({});
        } catch (e) {
            console.log('Note: Error deleting accounts:', e.message);
        }

        console.log('Deleting Users...');
        try {
            // Enforce deletion order handled by cascade usually, but manual explicit delete is safer
            const res = await prisma.user.deleteMany({});
            console.log(`✅ Successfully deleted ${res.count} users.`);
        } catch (e) {
            // Fallback for 'users' model name if mapped differently in client
            if (e.message.includes('dt does not exist') && prisma.users) {
                const res = await prisma.users.deleteMany({});
                console.log(`✅ Successfully deleted ${res.count} users (via .users).`);
            } else {
                throw e;
            }
        }

        console.log('🛡️  System clean and ready for registration testing.');

    } catch (error) {
        console.error('❌ Error during cleanup:', error);
        process.exit(1);
    } finally {
        await prisma.$disconnect();
    }
}

main();
